// <auto-generated />
using System;
using CPClient.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CPClient.Infra.Data.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20190225020451_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CPClient.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<string>("CPF");

                    b.Property<DateTime?>("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("NomeCompleto");

                    b.Property<string>("RG");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("CPClient.Domain.Entities.ClienteEndereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<string>("Bairro");

                    b.Property<int>("CEP");

                    b.Property<string>("CidadeUf");

                    b.Property<int>("ClienteId");

                    b.Property<string>("Complemento");

                    b.Property<DateTime?>("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<int>("EnderecoTipoId");

                    b.Property<string>("Logradouro");

                    b.Property<string>("Numero");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EnderecoTipoId");

                    b.ToTable("ClienteEndereco");
                });

            modelBuilder.Entity("CPClient.Domain.Entities.ClienteRedeSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<int>("ClienteId");

                    b.Property<DateTime?>("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<int>("RedeSocialTipoId");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("RedeSocialTipoId");

                    b.ToTable("ClienteRedeSocial");
                });

            modelBuilder.Entity("CPClient.Domain.Entities.ClienteTelefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<int>("ClienteId");

                    b.Property<DateTime?>("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<string>("Numero");

                    b.Property<int>("TelefoneTipoId");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TelefoneTipoId");

                    b.ToTable("ClienteTelefone");
                });

            modelBuilder.Entity("CPClient.Domain.Entities.EnderecoTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<DateTime?>("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("EnderecoTipo");
                });

            modelBuilder.Entity("CPClient.Domain.Entities.RedeSocialTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<DateTime?>("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("RedeSocialTipo");
                });

            modelBuilder.Entity("CPClient.Domain.Entities.TelefoneTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<DateTime?>("DataAtualizacao");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<string>("Descricao");

                    b.HasKey("Id");

                    b.ToTable("TelefoneTipo");
                });

            modelBuilder.Entity("CPClient.Domain.Entities.ClienteEndereco", b =>
                {
                    b.HasOne("CPClient.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Endereco")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CPClient.Domain.Entities.EnderecoTipo", "EnderecoTipo")
                        .WithMany("ClienteEndereco")
                        .HasForeignKey("EnderecoTipoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CPClient.Domain.Entities.ClienteRedeSocial", b =>
                {
                    b.HasOne("CPClient.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CPClient.Domain.Entities.RedeSocialTipo", "RedeSocialTipo")
                        .WithMany("ClienteRedeSocial")
                        .HasForeignKey("RedeSocialTipoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CPClient.Domain.Entities.ClienteTelefone", b =>
                {
                    b.HasOne("CPClient.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Telefone")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CPClient.Domain.Entities.TelefoneTipo", "TelefoneTipo")
                        .WithMany("ClienteTelefone")
                        .HasForeignKey("TelefoneTipoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
